### ISSUE TITLE
doc link

### ISSUE THREAD

**Issue by benjyz** [jcburley/joker#18]
I believe this is a format error in the readme

Dash docset: dash-feed://https%3A%2F%2Fraw.githubusercontent.com%2Fcandid82%2Fjoker%2Fmaster%2Fdocs%2Fjoker.xml

**Comment by jcburley** [comment]
I had trouble with that sort of URL at first too, but installing Dash (on my MacBook) fixed it. Might require rebooting the browser -- I can't remember.

So, for me, that URL works, though it takes me to the official Joker docs, not the `gostd` version of them.

I've just now fixed the URL to point to the `gostd` version of the docs -- thanks for bringing this to my attention!

Anyway, installing Dash should add support for the **dash-feed** protocol.

Please confirm that this solution works for you so I can Close this issue (or you can Close it if you like).

**Comment by jcburley** [comment]
Oh, here's the new URL:

dash-feed://https%3A%2F%2Fburleyarch.com%2Fjoker%2Fdocs%2Fjoker.xml

**Comment by jcburley** [comment]
This seems to work properly now.
